namespace LoginTo
{
    partial class RegisterForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(RegisterForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Background = new Bunifu.UI.WinForms.BunifuGradientPanel();
            PhoneNumberTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            BirthPlaceTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            NameTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            RegisterButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            PasswordTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            LogoPicture = new Bunifu.UI.WinForms.BunifuPictureBox();
            LoginLabel = new Bunifu.UI.WinForms.BunifuLabel();
            UsernameTextBox = new Bunifu.UI.WinForms.BunifuTextBox();
            BackButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            Background.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)LogoPicture).BeginInit();
            SuspendLayout();
            // 
            // Background
            // 
            Background.BackColor = Color.Transparent;
            Background.BackgroundImage = (Image)resources.GetObject("Background.BackgroundImage");
            Background.BackgroundImageLayout = ImageLayout.Stretch;
            Background.BorderRadius = 1;
            Background.Controls.Add(BackButton);
            Background.Controls.Add(PhoneNumberTextBox);
            Background.Controls.Add(BirthPlaceTextBox);
            Background.Controls.Add(NameTextBox);
            Background.Controls.Add(RegisterButton);
            Background.Controls.Add(PasswordTextBox);
            Background.Controls.Add(LogoPicture);
            Background.Controls.Add(LoginLabel);
            Background.Controls.Add(UsernameTextBox);
            Background.Dock = DockStyle.Fill;
            Background.Font = new Font("Segoe UI Semilight", 9F, FontStyle.Italic, GraphicsUnit.Point, 204);
            Background.GradientBottomLeft = Color.FromArgb(69, 104, 202);
            Background.GradientBottomRight = Color.FromArgb(208, 78, 214);
            Background.GradientTopLeft = Color.FromArgb(208, 78, 214);
            Background.GradientTopRight = Color.FromArgb(131, 77, 155);
            Background.Location = new Point(0, 0);
            Background.Name = "Background";
            Background.Quality = 10;
            Background.Size = new Size(421, 569);
            Background.TabIndex = 1;
            // 
            // PhoneNumberTextBox
            // 
            PhoneNumberTextBox.AcceptsReturn = false;
            PhoneNumberTextBox.AcceptsTab = false;
            PhoneNumberTextBox.AnimationSpeed = 200;
            PhoneNumberTextBox.AutoCompleteMode = AutoCompleteMode.None;
            PhoneNumberTextBox.AutoCompleteSource = AutoCompleteSource.None;
            PhoneNumberTextBox.AutoSizeHeight = true;
            PhoneNumberTextBox.BackColor = Color.White;
            PhoneNumberTextBox.BackgroundImage = (Image)resources.GetObject("PhoneNumberTextBox.BackgroundImage");
            PhoneNumberTextBox.BorderColorActive = Color.DodgerBlue;
            PhoneNumberTextBox.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            PhoneNumberTextBox.BorderColorHover = Color.FromArgb(105, 181, 255);
            PhoneNumberTextBox.BorderColorIdle = Color.Silver;
            PhoneNumberTextBox.BorderRadius = 1;
            PhoneNumberTextBox.BorderThickness = 1;
            PhoneNumberTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            PhoneNumberTextBox.CharacterCasing = CharacterCasing.Normal;
            PhoneNumberTextBox.DefaultFont = new Font("Segoe UI", 9.25F);
            PhoneNumberTextBox.DefaultText = "";
            PhoneNumberTextBox.FillColor = Color.White;
            PhoneNumberTextBox.HideSelection = true;
            PhoneNumberTextBox.IconLeft = Properties.Resources.icons8_user_50;
            PhoneNumberTextBox.IconLeftCursor = Cursors.IBeam;
            PhoneNumberTextBox.IconPadding = 10;
            PhoneNumberTextBox.IconRight = null;
            PhoneNumberTextBox.IconRightCursor = Cursors.IBeam;
            PhoneNumberTextBox.Location = new Point(48, 402);
            PhoneNumberTextBox.MaxLength = 32767;
            PhoneNumberTextBox.MinimumSize = new Size(1, 1);
            PhoneNumberTextBox.Modified = false;
            PhoneNumberTextBox.Multiline = false;
            PhoneNumberTextBox.Name = "PhoneNumberTextBox";
            stateProperties1.BorderColor = Color.DodgerBlue;
            stateProperties1.FillColor = Color.Empty;
            stateProperties1.ForeColor = Color.Empty;
            stateProperties1.PlaceholderForeColor = Color.Empty;
            PhoneNumberTextBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties2.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties2.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties2.PlaceholderForeColor = Color.DarkGray;
            PhoneNumberTextBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties3.FillColor = Color.Empty;
            stateProperties3.ForeColor = Color.Empty;
            stateProperties3.PlaceholderForeColor = Color.Empty;
            PhoneNumberTextBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = Color.Silver;
            stateProperties4.FillColor = Color.White;
            stateProperties4.ForeColor = Color.Empty;
            stateProperties4.PlaceholderForeColor = Color.Empty;
            PhoneNumberTextBox.OnIdleState = stateProperties4;
            PhoneNumberTextBox.Padding = new Padding(3);
            PhoneNumberTextBox.PasswordChar = '\0';
            PhoneNumberTextBox.PlaceholderForeColor = Color.Silver;
            PhoneNumberTextBox.PlaceholderText = "PhoneNumber";
            PhoneNumberTextBox.ReadOnly = false;
            PhoneNumberTextBox.ScrollBars = ScrollBars.None;
            PhoneNumberTextBox.SelectedText = "";
            PhoneNumberTextBox.SelectionLength = 0;
            PhoneNumberTextBox.SelectionStart = 0;
            PhoneNumberTextBox.ShortcutsEnabled = true;
            PhoneNumberTextBox.Size = new Size(325, 43);
            PhoneNumberTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            PhoneNumberTextBox.TabIndex = 10;
            PhoneNumberTextBox.TextAlign = HorizontalAlignment.Left;
            PhoneNumberTextBox.TextMarginBottom = 0;
            PhoneNumberTextBox.TextMarginLeft = 3;
            PhoneNumberTextBox.TextMarginTop = 1;
            PhoneNumberTextBox.TextPlaceholder = "PhoneNumber";
            PhoneNumberTextBox.UseSystemPasswordChar = false;
            PhoneNumberTextBox.WordWrap = true;
            // 
            // BirthPlaceTextBox
            // 
            BirthPlaceTextBox.AcceptsReturn = false;
            BirthPlaceTextBox.AcceptsTab = false;
            BirthPlaceTextBox.AnimationSpeed = 200;
            BirthPlaceTextBox.AutoCompleteMode = AutoCompleteMode.None;
            BirthPlaceTextBox.AutoCompleteSource = AutoCompleteSource.None;
            BirthPlaceTextBox.AutoSizeHeight = true;
            BirthPlaceTextBox.BackColor = Color.White;
            BirthPlaceTextBox.BackgroundImage = (Image)resources.GetObject("BirthPlaceTextBox.BackgroundImage");
            BirthPlaceTextBox.BorderColorActive = Color.DodgerBlue;
            BirthPlaceTextBox.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            BirthPlaceTextBox.BorderColorHover = Color.FromArgb(105, 181, 255);
            BirthPlaceTextBox.BorderColorIdle = Color.Silver;
            BirthPlaceTextBox.BorderRadius = 1;
            BirthPlaceTextBox.BorderThickness = 1;
            BirthPlaceTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            BirthPlaceTextBox.CharacterCasing = CharacterCasing.Normal;
            BirthPlaceTextBox.DefaultFont = new Font("Segoe UI", 9.25F);
            BirthPlaceTextBox.DefaultText = "";
            BirthPlaceTextBox.FillColor = Color.White;
            BirthPlaceTextBox.HideSelection = true;
            BirthPlaceTextBox.IconLeft = Properties.Resources.icons8_user_50;
            BirthPlaceTextBox.IconLeftCursor = Cursors.IBeam;
            BirthPlaceTextBox.IconPadding = 10;
            BirthPlaceTextBox.IconRight = null;
            BirthPlaceTextBox.IconRightCursor = Cursors.IBeam;
            BirthPlaceTextBox.Location = new Point(48, 342);
            BirthPlaceTextBox.MaxLength = 32767;
            BirthPlaceTextBox.MinimumSize = new Size(1, 1);
            BirthPlaceTextBox.Modified = false;
            BirthPlaceTextBox.Multiline = false;
            BirthPlaceTextBox.Name = "BirthPlaceTextBox";
            stateProperties5.BorderColor = Color.DodgerBlue;
            stateProperties5.FillColor = Color.Empty;
            stateProperties5.ForeColor = Color.Empty;
            stateProperties5.PlaceholderForeColor = Color.Empty;
            BirthPlaceTextBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties6.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties6.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties6.PlaceholderForeColor = Color.DarkGray;
            BirthPlaceTextBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties7.FillColor = Color.Empty;
            stateProperties7.ForeColor = Color.Empty;
            stateProperties7.PlaceholderForeColor = Color.Empty;
            BirthPlaceTextBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = Color.Silver;
            stateProperties8.FillColor = Color.White;
            stateProperties8.ForeColor = Color.Empty;
            stateProperties8.PlaceholderForeColor = Color.Empty;
            BirthPlaceTextBox.OnIdleState = stateProperties8;
            BirthPlaceTextBox.Padding = new Padding(3);
            BirthPlaceTextBox.PasswordChar = '\0';
            BirthPlaceTextBox.PlaceholderForeColor = Color.Silver;
            BirthPlaceTextBox.PlaceholderText = "Birth Place";
            BirthPlaceTextBox.ReadOnly = false;
            BirthPlaceTextBox.ScrollBars = ScrollBars.None;
            BirthPlaceTextBox.SelectedText = "";
            BirthPlaceTextBox.SelectionLength = 0;
            BirthPlaceTextBox.SelectionStart = 0;
            BirthPlaceTextBox.ShortcutsEnabled = true;
            BirthPlaceTextBox.Size = new Size(325, 43);
            BirthPlaceTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            BirthPlaceTextBox.TabIndex = 9;
            BirthPlaceTextBox.TextAlign = HorizontalAlignment.Left;
            BirthPlaceTextBox.TextMarginBottom = 0;
            BirthPlaceTextBox.TextMarginLeft = 3;
            BirthPlaceTextBox.TextMarginTop = 1;
            BirthPlaceTextBox.TextPlaceholder = "Birth Place";
            BirthPlaceTextBox.UseSystemPasswordChar = false;
            BirthPlaceTextBox.WordWrap = true;
            // 
            // NameTextBox
            // 
            NameTextBox.AcceptsReturn = false;
            NameTextBox.AcceptsTab = false;
            NameTextBox.AnimationSpeed = 200;
            NameTextBox.AutoCompleteMode = AutoCompleteMode.None;
            NameTextBox.AutoCompleteSource = AutoCompleteSource.None;
            NameTextBox.AutoSizeHeight = true;
            NameTextBox.BackColor = Color.White;
            NameTextBox.BackgroundImage = (Image)resources.GetObject("NameTextBox.BackgroundImage");
            NameTextBox.BorderColorActive = Color.DodgerBlue;
            NameTextBox.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            NameTextBox.BorderColorHover = Color.FromArgb(105, 181, 255);
            NameTextBox.BorderColorIdle = Color.Silver;
            NameTextBox.BorderRadius = 1;
            NameTextBox.BorderThickness = 1;
            NameTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            NameTextBox.CharacterCasing = CharacterCasing.Normal;
            NameTextBox.DefaultFont = new Font("Segoe UI", 9.25F);
            NameTextBox.DefaultText = "";
            NameTextBox.FillColor = Color.White;
            NameTextBox.HideSelection = true;
            NameTextBox.IconLeft = Properties.Resources.icons8_user_50;
            NameTextBox.IconLeftCursor = Cursors.IBeam;
            NameTextBox.IconPadding = 10;
            NameTextBox.IconRight = null;
            NameTextBox.IconRightCursor = Cursors.IBeam;
            NameTextBox.Location = new Point(48, 282);
            NameTextBox.MaxLength = 32767;
            NameTextBox.MinimumSize = new Size(1, 1);
            NameTextBox.Modified = false;
            NameTextBox.Multiline = false;
            NameTextBox.Name = "NameTextBox";
            stateProperties9.BorderColor = Color.DodgerBlue;
            stateProperties9.FillColor = Color.Empty;
            stateProperties9.ForeColor = Color.Empty;
            stateProperties9.PlaceholderForeColor = Color.Empty;
            NameTextBox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties10.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties10.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties10.PlaceholderForeColor = Color.DarkGray;
            NameTextBox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties11.FillColor = Color.Empty;
            stateProperties11.ForeColor = Color.Empty;
            stateProperties11.PlaceholderForeColor = Color.Empty;
            NameTextBox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = Color.Silver;
            stateProperties12.FillColor = Color.White;
            stateProperties12.ForeColor = Color.Empty;
            stateProperties12.PlaceholderForeColor = Color.Empty;
            NameTextBox.OnIdleState = stateProperties12;
            NameTextBox.Padding = new Padding(3);
            NameTextBox.PasswordChar = '\0';
            NameTextBox.PlaceholderForeColor = Color.Silver;
            NameTextBox.PlaceholderText = "Surname Name ";
            NameTextBox.ReadOnly = false;
            NameTextBox.ScrollBars = ScrollBars.None;
            NameTextBox.SelectedText = "";
            NameTextBox.SelectionLength = 0;
            NameTextBox.SelectionStart = 0;
            NameTextBox.ShortcutsEnabled = true;
            NameTextBox.Size = new Size(325, 43);
            NameTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            NameTextBox.TabIndex = 8;
            NameTextBox.TextAlign = HorizontalAlignment.Left;
            NameTextBox.TextMarginBottom = 0;
            NameTextBox.TextMarginLeft = 3;
            NameTextBox.TextMarginTop = 1;
            NameTextBox.TextPlaceholder = "Surname Name ";
            NameTextBox.UseSystemPasswordChar = false;
            NameTextBox.WordWrap = true;
            // 
            // RegisterButton
            // 
            RegisterButton.AllowAnimations = true;
            RegisterButton.AllowMouseEffects = true;
            RegisterButton.AllowToggling = false;
            RegisterButton.AnimationSpeed = 200;
            RegisterButton.AutoGenerateColors = false;
            RegisterButton.AutoRoundBorders = false;
            RegisterButton.AutoSizeLeftIcon = true;
            RegisterButton.AutoSizeRightIcon = true;
            RegisterButton.BackColor = Color.Transparent;
            RegisterButton.BackColor1 = Color.DodgerBlue;
            RegisterButton.BackgroundImage = (Image)resources.GetObject("RegisterButton.BackgroundImage");
            RegisterButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            RegisterButton.ButtonText = "Register";
            RegisterButton.ButtonTextMarginLeft = 0;
            RegisterButton.ColorContrastOnClick = 45;
            RegisterButton.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            RegisterButton.CustomizableEdges = borderEdges2;
            RegisterButton.DialogResult = DialogResult.None;
            RegisterButton.DisabledBorderColor = Color.Silver;
            RegisterButton.DisabledFillColor = Color.DodgerBlue;
            RegisterButton.DisabledForecolor = Color.White;
            RegisterButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            RegisterButton.Font = new Font("Segoe UI", 24F, FontStyle.Bold, GraphicsUnit.Point, 204);
            RegisterButton.ForeColor = Color.White;
            RegisterButton.IconLeftAlign = ContentAlignment.MiddleLeft;
            RegisterButton.IconLeftCursor = Cursors.Default;
            RegisterButton.IconLeftPadding = new Padding(11, 3, 3, 3);
            RegisterButton.IconMarginLeft = 11;
            RegisterButton.IconPadding = 10;
            RegisterButton.IconRightAlign = ContentAlignment.MiddleRight;
            RegisterButton.IconRightCursor = Cursors.Default;
            RegisterButton.IconRightPadding = new Padding(3, 3, 7, 3);
            RegisterButton.IconSize = 25;
            RegisterButton.IdleBorderColor = Color.Silver;
            RegisterButton.IdleBorderRadius = 1;
            RegisterButton.IdleBorderThickness = 1;
            RegisterButton.IdleFillColor = Color.DodgerBlue;
            RegisterButton.IdleIconLeftImage = null;
            RegisterButton.IdleIconRightImage = null;
            RegisterButton.IndicateFocus = false;
            RegisterButton.Location = new Point(48, 451);
            RegisterButton.Name = "RegisterButton";
            RegisterButton.OnDisabledState.BorderColor = Color.Silver;
            RegisterButton.OnDisabledState.BorderRadius = 1;
            RegisterButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            RegisterButton.OnDisabledState.BorderThickness = 1;
            RegisterButton.OnDisabledState.FillColor = Color.DodgerBlue;
            RegisterButton.OnDisabledState.ForeColor = Color.White;
            RegisterButton.OnDisabledState.IconLeftImage = null;
            RegisterButton.OnDisabledState.IconRightImage = null;
            RegisterButton.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
            RegisterButton.onHoverState.BorderRadius = 1;
            RegisterButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            RegisterButton.onHoverState.BorderThickness = 1;
            RegisterButton.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
            RegisterButton.onHoverState.ForeColor = Color.White;
            RegisterButton.onHoverState.IconLeftImage = null;
            RegisterButton.onHoverState.IconRightImage = null;
            RegisterButton.OnIdleState.BorderColor = Color.Silver;
            RegisterButton.OnIdleState.BorderRadius = 1;
            RegisterButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            RegisterButton.OnIdleState.BorderThickness = 1;
            RegisterButton.OnIdleState.FillColor = Color.DodgerBlue;
            RegisterButton.OnIdleState.ForeColor = Color.White;
            RegisterButton.OnIdleState.IconLeftImage = null;
            RegisterButton.OnIdleState.IconRightImage = null;
            RegisterButton.OnPressedState.BorderColor = Color.Silver;
            RegisterButton.OnPressedState.BorderRadius = 1;
            RegisterButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            RegisterButton.OnPressedState.BorderThickness = 1;
            RegisterButton.OnPressedState.FillColor = Color.DodgerBlue;
            RegisterButton.OnPressedState.ForeColor = Color.White;
            RegisterButton.OnPressedState.IconLeftImage = null;
            RegisterButton.OnPressedState.IconRightImage = null;
            RegisterButton.Size = new Size(325, 54);
            RegisterButton.TabIndex = 7;
            RegisterButton.TextAlign = ContentAlignment.MiddleCenter;
            RegisterButton.TextAlignment = HorizontalAlignment.Center;
            RegisterButton.TextMarginLeft = 0;
            RegisterButton.TextPadding = new Padding(0);
            RegisterButton.UseDefaultRadiusAndThickness = true;
            RegisterButton.Click += RegisterButton_Click;
            // 
            // PasswordTextBox
            // 
            PasswordTextBox.AcceptsReturn = false;
            PasswordTextBox.AcceptsTab = false;
            PasswordTextBox.AnimationSpeed = 200;
            PasswordTextBox.AutoCompleteMode = AutoCompleteMode.None;
            PasswordTextBox.AutoCompleteSource = AutoCompleteSource.None;
            PasswordTextBox.AutoSizeHeight = true;
            PasswordTextBox.BackColor = Color.White;
            PasswordTextBox.BackgroundImage = (Image)resources.GetObject("PasswordTextBox.BackgroundImage");
            PasswordTextBox.BorderColorActive = Color.DodgerBlue;
            PasswordTextBox.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            PasswordTextBox.BorderColorHover = Color.FromArgb(105, 181, 255);
            PasswordTextBox.BorderColorIdle = Color.Silver;
            PasswordTextBox.BorderRadius = 1;
            PasswordTextBox.BorderThickness = 1;
            PasswordTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            PasswordTextBox.CharacterCasing = CharacterCasing.Normal;
            PasswordTextBox.DefaultFont = new Font("Segoe UI", 9.25F);
            PasswordTextBox.DefaultText = "";
            PasswordTextBox.FillColor = Color.White;
            PasswordTextBox.HideSelection = true;
            PasswordTextBox.IconLeft = (Image)resources.GetObject("PasswordTextBox.IconLeft");
            PasswordTextBox.IconLeftCursor = Cursors.IBeam;
            PasswordTextBox.IconPadding = 10;
            PasswordTextBox.IconRight = null;
            PasswordTextBox.IconRightCursor = Cursors.IBeam;
            PasswordTextBox.Location = new Point(48, 222);
            PasswordTextBox.MaxLength = 32767;
            PasswordTextBox.MinimumSize = new Size(1, 1);
            PasswordTextBox.Modified = false;
            PasswordTextBox.Multiline = false;
            PasswordTextBox.Name = "PasswordTextBox";
            stateProperties13.BorderColor = Color.DodgerBlue;
            stateProperties13.FillColor = Color.Empty;
            stateProperties13.ForeColor = Color.Empty;
            stateProperties13.PlaceholderForeColor = Color.Empty;
            PasswordTextBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties14.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties14.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties14.PlaceholderForeColor = Color.DarkGray;
            PasswordTextBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties15.FillColor = Color.Empty;
            stateProperties15.ForeColor = Color.Empty;
            stateProperties15.PlaceholderForeColor = Color.Empty;
            PasswordTextBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = Color.Silver;
            stateProperties16.FillColor = Color.White;
            stateProperties16.ForeColor = Color.Empty;
            stateProperties16.PlaceholderForeColor = Color.Empty;
            PasswordTextBox.OnIdleState = stateProperties16;
            PasswordTextBox.Padding = new Padding(3);
            PasswordTextBox.PasswordChar = '\0';
            PasswordTextBox.PlaceholderForeColor = Color.Silver;
            PasswordTextBox.PlaceholderText = "Your Password";
            PasswordTextBox.ReadOnly = false;
            PasswordTextBox.ScrollBars = ScrollBars.None;
            PasswordTextBox.SelectedText = "";
            PasswordTextBox.SelectionLength = 0;
            PasswordTextBox.SelectionStart = 0;
            PasswordTextBox.ShortcutsEnabled = true;
            PasswordTextBox.Size = new Size(325, 43);
            PasswordTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            PasswordTextBox.TabIndex = 3;
            PasswordTextBox.TextAlign = HorizontalAlignment.Left;
            PasswordTextBox.TextMarginBottom = 0;
            PasswordTextBox.TextMarginLeft = 3;
            PasswordTextBox.TextMarginTop = 1;
            PasswordTextBox.TextPlaceholder = "Your Password";
            PasswordTextBox.UseSystemPasswordChar = false;
            PasswordTextBox.WordWrap = true;
            // 
            // LogoPicture
            // 
            LogoPicture.AllowFocused = false;
            LogoPicture.Anchor = AnchorStyles.None;
            LogoPicture.AutoSizeHeight = true;
            LogoPicture.BorderRadius = 61;
            LogoPicture.Image = (Image)resources.GetObject("LogoPicture.Image");
            LogoPicture.IsCircle = true;
            LogoPicture.Location = new Point(142, 0);
            LogoPicture.Name = "LogoPicture";
            LogoPicture.Size = new Size(122, 122);
            LogoPicture.SizeMode = PictureBoxSizeMode.Zoom;
            LogoPicture.TabIndex = 2;
            LogoPicture.TabStop = false;
            LogoPicture.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // LoginLabel
            // 
            LoginLabel.AllowParentOverrides = false;
            LoginLabel.AutoEllipsis = false;
            LoginLabel.CursorType = Cursors.Default;
            LoginLabel.Font = new Font("Segoe UI Black", 20F, FontStyle.Bold, GraphicsUnit.Point, 204);
            LoginLabel.Location = new Point(101, 111);
            LoginLabel.Name = "LoginLabel";
            LoginLabel.RightToLeft = RightToLeft.No;
            LoginLabel.Size = new Size(201, 45);
            LoginLabel.TabIndex = 1;
            LoginLabel.Text = "Registration";
            LoginLabel.TextAlignment = ContentAlignment.TopLeft;
            LoginLabel.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // UsernameTextBox
            // 
            UsernameTextBox.AcceptsReturn = false;
            UsernameTextBox.AcceptsTab = false;
            UsernameTextBox.AnimationSpeed = 200;
            UsernameTextBox.AutoCompleteMode = AutoCompleteMode.None;
            UsernameTextBox.AutoCompleteSource = AutoCompleteSource.None;
            UsernameTextBox.AutoSizeHeight = true;
            UsernameTextBox.BackColor = Color.White;
            UsernameTextBox.BackgroundImage = (Image)resources.GetObject("UsernameTextBox.BackgroundImage");
            UsernameTextBox.BorderColorActive = Color.DodgerBlue;
            UsernameTextBox.BorderColorDisabled = Color.FromArgb(204, 204, 204);
            UsernameTextBox.BorderColorHover = Color.FromArgb(105, 181, 255);
            UsernameTextBox.BorderColorIdle = Color.Silver;
            UsernameTextBox.BorderRadius = 1;
            UsernameTextBox.BorderThickness = 1;
            UsernameTextBox.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            UsernameTextBox.CharacterCasing = CharacterCasing.Normal;
            UsernameTextBox.DefaultFont = new Font("Segoe UI", 9.25F);
            UsernameTextBox.DefaultText = "";
            UsernameTextBox.FillColor = Color.White;
            UsernameTextBox.HideSelection = true;
            UsernameTextBox.IconLeft = Properties.Resources.icons8_user_50;
            UsernameTextBox.IconLeftCursor = Cursors.IBeam;
            UsernameTextBox.IconPadding = 10;
            UsernameTextBox.IconRight = null;
            UsernameTextBox.IconRightCursor = Cursors.IBeam;
            UsernameTextBox.Location = new Point(48, 162);
            UsernameTextBox.MaxLength = 32767;
            UsernameTextBox.MinimumSize = new Size(1, 1);
            UsernameTextBox.Modified = false;
            UsernameTextBox.Multiline = false;
            UsernameTextBox.Name = "UsernameTextBox";
            stateProperties17.BorderColor = Color.DodgerBlue;
            stateProperties17.FillColor = Color.Empty;
            stateProperties17.ForeColor = Color.Empty;
            stateProperties17.PlaceholderForeColor = Color.Empty;
            UsernameTextBox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = Color.FromArgb(204, 204, 204);
            stateProperties18.FillColor = Color.FromArgb(240, 240, 240);
            stateProperties18.ForeColor = Color.FromArgb(109, 109, 109);
            stateProperties18.PlaceholderForeColor = Color.DarkGray;
            UsernameTextBox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = Color.FromArgb(105, 181, 255);
            stateProperties19.FillColor = Color.Empty;
            stateProperties19.ForeColor = Color.Empty;
            stateProperties19.PlaceholderForeColor = Color.Empty;
            UsernameTextBox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = Color.Silver;
            stateProperties20.FillColor = Color.White;
            stateProperties20.ForeColor = Color.Empty;
            stateProperties20.PlaceholderForeColor = Color.Empty;
            UsernameTextBox.OnIdleState = stateProperties20;
            UsernameTextBox.Padding = new Padding(3);
            UsernameTextBox.PasswordChar = '\0';
            UsernameTextBox.PlaceholderForeColor = Color.Silver;
            UsernameTextBox.PlaceholderText = "Enter Username";
            UsernameTextBox.ReadOnly = false;
            UsernameTextBox.ScrollBars = ScrollBars.None;
            UsernameTextBox.SelectedText = "";
            UsernameTextBox.SelectionLength = 0;
            UsernameTextBox.SelectionStart = 0;
            UsernameTextBox.ShortcutsEnabled = true;
            UsernameTextBox.Size = new Size(325, 43);
            UsernameTextBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            UsernameTextBox.TabIndex = 0;
            UsernameTextBox.TextAlign = HorizontalAlignment.Left;
            UsernameTextBox.TextMarginBottom = 0;
            UsernameTextBox.TextMarginLeft = 3;
            UsernameTextBox.TextMarginTop = 1;
            UsernameTextBox.TextPlaceholder = "Enter Username";
            UsernameTextBox.UseSystemPasswordChar = false;
            UsernameTextBox.WordWrap = true;
            // 
            // BackButton
            // 
            BackButton.AllowAnimations = true;
            BackButton.AllowMouseEffects = true;
            BackButton.AllowToggling = false;
            BackButton.AnimationSpeed = 200;
            BackButton.AutoGenerateColors = false;
            BackButton.AutoRoundBorders = false;
            BackButton.AutoSizeLeftIcon = true;
            BackButton.AutoSizeRightIcon = true;
            BackButton.BackColor = Color.Transparent;
            BackButton.BackColor1 = Color.DodgerBlue;
            BackButton.BackgroundImage = (Image)resources.GetObject("BackButton.BackgroundImage");
            BackButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            BackButton.ButtonText = "Back";
            BackButton.ButtonTextMarginLeft = 0;
            BackButton.ColorContrastOnClick = 45;
            BackButton.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            BackButton.CustomizableEdges = borderEdges1;
            BackButton.DialogResult = DialogResult.None;
            BackButton.DisabledBorderColor = Color.Silver;
            BackButton.DisabledFillColor = Color.DodgerBlue;
            BackButton.DisabledForecolor = Color.White;
            BackButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            BackButton.Font = new Font("Segoe UI", 24F, FontStyle.Bold, GraphicsUnit.Point, 204);
            BackButton.ForeColor = Color.White;
            BackButton.IconLeftAlign = ContentAlignment.MiddleLeft;
            BackButton.IconLeftCursor = Cursors.Default;
            BackButton.IconLeftPadding = new Padding(11, 3, 3, 3);
            BackButton.IconMarginLeft = 11;
            BackButton.IconPadding = 10;
            BackButton.IconRightAlign = ContentAlignment.MiddleRight;
            BackButton.IconRightCursor = Cursors.Default;
            BackButton.IconRightPadding = new Padding(3, 3, 7, 3);
            BackButton.IconSize = 25;
            BackButton.IdleBorderColor = Color.Silver;
            BackButton.IdleBorderRadius = 1;
            BackButton.IdleBorderThickness = 1;
            BackButton.IdleFillColor = Color.DodgerBlue;
            BackButton.IdleIconLeftImage = null;
            BackButton.IdleIconRightImage = null;
            BackButton.IndicateFocus = false;
            BackButton.Location = new Point(48, 511);
            BackButton.Name = "BackButton";
            BackButton.OnDisabledState.BorderColor = Color.Silver;
            BackButton.OnDisabledState.BorderRadius = 1;
            BackButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            BackButton.OnDisabledState.BorderThickness = 1;
            BackButton.OnDisabledState.FillColor = Color.DodgerBlue;
            BackButton.OnDisabledState.ForeColor = Color.White;
            BackButton.OnDisabledState.IconLeftImage = null;
            BackButton.OnDisabledState.IconRightImage = null;
            BackButton.onHoverState.BorderColor = Color.FromArgb(105, 181, 255);
            BackButton.onHoverState.BorderRadius = 1;
            BackButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            BackButton.onHoverState.BorderThickness = 1;
            BackButton.onHoverState.FillColor = Color.FromArgb(105, 181, 255);
            BackButton.onHoverState.ForeColor = Color.White;
            BackButton.onHoverState.IconLeftImage = null;
            BackButton.onHoverState.IconRightImage = null;
            BackButton.OnIdleState.BorderColor = Color.Silver;
            BackButton.OnIdleState.BorderRadius = 1;
            BackButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            BackButton.OnIdleState.BorderThickness = 1;
            BackButton.OnIdleState.FillColor = Color.DodgerBlue;
            BackButton.OnIdleState.ForeColor = Color.White;
            BackButton.OnIdleState.IconLeftImage = null;
            BackButton.OnIdleState.IconRightImage = null;
            BackButton.OnPressedState.BorderColor = Color.Silver;
            BackButton.OnPressedState.BorderRadius = 1;
            BackButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            BackButton.OnPressedState.BorderThickness = 1;
            BackButton.OnPressedState.FillColor = Color.DodgerBlue;
            BackButton.OnPressedState.ForeColor = Color.White;
            BackButton.OnPressedState.IconLeftImage = null;
            BackButton.OnPressedState.IconRightImage = null;
            BackButton.Size = new Size(325, 46);
            BackButton.TabIndex = 11;
            BackButton.TextAlign = ContentAlignment.MiddleCenter;
            BackButton.TextAlignment = HorizontalAlignment.Center;
            BackButton.TextMarginLeft = 0;
            BackButton.TextPadding = new Padding(0);
            BackButton.UseDefaultRadiusAndThickness = true;
            BackButton.Click += BackButton_Click;
            // 
            // RegisterForm
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(421, 569);
            Controls.Add(Background);
            FormBorderStyle = FormBorderStyle.None;
            MinimizeBox = false;
            Name = "RegisterForm";
            StartPosition = FormStartPosition.CenterScreen;
            Text = "RegisterForm";
            Background.ResumeLayout(false);
            Background.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)LogoPicture).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel Background;
        private Bunifu.UI.WinForms.BunifuTextBox PasswordTextBox;
        private Bunifu.UI.WinForms.BunifuPictureBox LogoPicture;
        private Bunifu.UI.WinForms.BunifuLabel LoginLabel;
        private Bunifu.UI.WinForms.BunifuTextBox UsernameTextBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 RegisterButton;
        private Bunifu.UI.WinForms.BunifuTextBox PhoneNumberTextBox;
        private Bunifu.UI.WinForms.BunifuTextBox BirthPlaceTextBox;
        private Bunifu.UI.WinForms.BunifuTextBox NameTextBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 BackButton;
    }
}